import '../models/rule.dart';

class DefaultRules {
  static List<RuleDefinition> create() => [
    RuleDefinition(
      id: 'exit',
      kind: RuleKind.exit,
      name: '跑路纪律',
      summary: '缩量破位减半、巨量减半、放量破位清仓，形态衰竭时减仓。',
      description: '上升趋势跌破均线或箱体支撑时执行仓位纪律；巨量与破位叠加时提高卖出优先级。',
      enabled: true,
      version: 1,
      parameters: const [
        RuleParameter(
          key: 'maDays',
          label: '趋势均线',
          type: RuleParameterType.integer,
          defaultValue: 5,
          min: 3,
          max: 30,
          unit: '日',
          description: '用于判断趋势破位的移动平均线周期',
        ),
        RuleParameter(
          key: 'boxDays',
          label: '箱体窗口',
          type: RuleParameterType.integer,
          defaultValue: 20,
          min: 5,
          max: 120,
          unit: '日',
          description: '用于估算箱体上下沿的窗口',
        ),
        RuleParameter(
          key: 'shrinkRatio',
          label: '缩量比例',
          type: RuleParameterType.decimal,
          defaultValue: 0.85,
          min: 0.2,
          max: 1,
          unit: '倍',
          description: '今日量低于近几日均量的比例',
        ),
        RuleParameter(
          key: 'hugeVolumeRatio',
          label: '巨量比例',
          type: RuleParameterType.decimal,
          defaultValue: 1.25,
          min: 1,
          max: 5,
          unit: '倍',
          description: '今日量相对近5日均量阈值',
        ),
        RuleParameter(
          key: 'shadowRatio',
          label: '长影线比例',
          type: RuleParameterType.percent,
          defaultValue: 45,
          min: 20,
          max: 90,
          unit: '%',
          description: '影线占当日振幅的比例',
        ),
      ],
      values: const {
        'maDays': 5,
        'boxDays': 20,
        'shrinkRatio': 0.85,
        'hugeVolumeRatio': 1.25,
        'shadowRatio': 45,
      },
    ),
    RuleDefinition(
      id: 'gap_up',
      kind: RuleKind.gapUp,
      name: '跳空高开纪律',
      summary: '跳空冲高先减仓，小实体或长影线提示承接不足。',
      description: '结合日线跳空和开盘前20分钟分时，识别冲高兑现、回落和诱多风险。',
      enabled: true,
      version: 1,
      parameters: const [
        RuleParameter(
          key: 'gapPercent',
          label: '跳空阈值',
          type: RuleParameterType.percent,
          defaultValue: 2,
          min: 0.5,
          max: 15,
          unit: '%',
          description: '今日开盘相对昨收的最低跳空幅度',
        ),
        RuleParameter(
          key: 'strongGapPercent',
          label: '强跳空阈值',
          type: RuleParameterType.percent,
          defaultValue: 3,
          min: 1,
          max: 20,
          unit: '%',
          description: '触发开盘冲高兑现提醒的幅度',
        ),
        RuleParameter(
          key: 'smallBodyRatio',
          label: '小实体比例',
          type: RuleParameterType.percent,
          defaultValue: 35,
          min: 5,
          max: 60,
          unit: '%',
          description: '实体占全天振幅小于此值视为承接不足',
        ),
        RuleParameter(
          key: 'shadowRatio',
          label: '长影线比例',
          type: RuleParameterType.percent,
          defaultValue: 40,
          min: 20,
          max: 90,
          unit: '%',
          description: '上下影线占全天振幅阈值',
        ),
      ],
      values: const {
        'gapPercent': 2,
        'strongGapPercent': 3,
        'smallBodyRatio': 35,
        'shadowRatio': 40,
      },
    ),
    RuleDefinition(
      id: 'second_high',
      kind: RuleKind.secondHigh,
      name: '二高点与回撤修复',
      summary: '深跌后等待二高点，急跌标的以轻仓修复和减仓为主。',
      description: '依据阶段回撤、峰值距离和修复速度识别二高点候选。',
      enabled: true,
      version: 1,
      parameters: const [
        RuleParameter(
          key: 'lookbackDays',
          label: '高点窗口',
          type: RuleParameterType.integer,
          defaultValue: 90,
          min: 30,
          max: 250,
          unit: '日',
          description: '寻找阶段高点的回看窗口',
        ),
        RuleParameter(
          key: 'deepDropPercent',
          label: '深度回撤',
          type: RuleParameterType.percent,
          defaultValue: 18,
          min: 5,
          max: 70,
          unit: '%',
          description: '进入修复观察的最低回撤幅度',
        ),
        RuleParameter(
          key: 'secondHighPercent',
          label: '二高点上限',
          type: RuleParameterType.percent,
          defaultValue: 98,
          min: 60,
          max: 99,
          unit: '%',
          description: '二高点相对前高的最高比例',
        ),
        RuleParameter(
          key: 'nearPercent',
          label: '接近二高点',
          type: RuleParameterType.percent,
          defaultValue: 97,
          min: 80,
          max: 100,
          unit: '%',
          description: '当前价接近反弹高点的比例',
        ),
      ],
      values: const {
        'lookbackDays': 90,
        'deepDropPercent': 18,
        'secondHighPercent': 98,
        'nearPercent': 97,
      },
    ),
    RuleDefinition(
      id: 'sector_corr',
      kind: RuleKind.sectorCorrelation,
      name: '板块联动因子',
      summary: '银行与证券同步急拉时，提示科技方向资金切换风险。',
      description: '使用板块指数或代表股三日涨幅判断金融与科技的跷跷板效应。',
      enabled: true,
      version: 1,
      parameters: const [
        RuleParameter(
          key: 'days',
          label: '联动窗口',
          type: RuleParameterType.integer,
          defaultValue: 3,
          min: 1,
          max: 10,
          unit: '日',
          description: '计算银行证券短期涨幅的窗口',
        ),
        RuleParameter(
          key: 'surgePercent',
          label: '急拉阈值',
          type: RuleParameterType.percent,
          defaultValue: 4,
          min: 1,
          max: 20,
          unit: '%',
          description: '银行和证券均需达到的短期涨幅',
        ),
      ],
      values: const {'days': 3, 'surgePercent': 4},
    ),
  ];
}
